# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

## ------------------------------------------- DataProvider Plugin properties ------------------------------------------------------------
mosip.certify.integration.scan-base-package=io.mosip.certify.mosipid.integration
mosip.certify.integration.audit-plugin=IdaAuditPluginImpl
mosip.certify.integration.data-provider-plugin=IdaDataProviderPluginImpl
mosip.certify.plugin-mode=DataProvider

# set custom VC expiry, supports limited subset of ISO-8601 Duration format starting from days to seconds
# E.g. P21dT1h-2m3s for more information check javadoc of Duration.parse(String)
mosip.certify.data-provider-plugin.vc-expiry-duration=P730d
# Cache-Control max-age value for rendering templates
mosip.certify.rendering-template.cache-max-age-days=1

# Properties to fetch data from IDA
mosip.certify.ida.kyc-exchange-id=mosip.identity.kycexchange
mosip.certify.authenticator.ida-version=1.0
mosip.certify.authenticator.ida.kyc-exchange-url=https://${mosip.api.cre.internal.host}/idauthentication/v1/kyc-exchange/delegated/${mosip.certify.misp.license.key}/

#mosip.certify.data-provider-plugin.did-url=did:web:inji.github.io:inji-config:dev-int-inji:mosipid-identity
#mosip.certify.data-provider-plugin.id-field-prefix-uri=https://mosip.io/credential/

## ------------------------------------------- VCIssuance Plugin properties ------------------------------------------------------------
#mosip.certify.integration.scan-base-package=io.mosip.certify.mosipid.integration
#mosip.certify.integration.audit-plugin=IdaAuditPluginImpl
#mosip.certify.integration.vci-plugin=IdaVCIssuancePluginImpl
#mosip.certify.plugin-mode=VCIssuance

# Properties to get VC from IDA
#mosip.certify.ida.vci-exchange-id=mosip.identity.vciexchange
#mosip.certify.ida.vci-exchange-version=1.0
#mosip.certify.ida.vci-exchange-url=https://${mosip.api.cre.internal.host}/idauthentication/v1/vci-exchange/delegated/${mosip.certify.misp.license.key}/

## ---------------------------------------- Cache configuration [this is overriding default configuration present in certify default properties] [This block will be removed in next release] --------------------------------------------------------
spring.cache.type=redis
spring.cache.cache-names=${mosip.certify.cache.names}
spring.data.redis.host=redis-master.redis.svc.cluster.local
spring.data.redis.port=6379
management.health.redis.enabled=false
spring.data.redis.password=DcpxKDSfKn

## ------------------------------------------- Plugin specific usecase properties ------------------------------------------------------------
mosip.certify.cache.secure.individual-id=false
mosip.certify.cache.store.individual-id=true
mosip.certify.cache.security.algorithm-name=AES/ECB/PKCS5Padding

mosip.certify.misp.license.key=${mosip.certify.misp.key}

mosip.certify.ida.vci-user-info-cache=userinfo

mosip.certify.authenticator.ida.auth-token-url=https://${mosip.api.cre.internal.host}/v1/authmanager/authenticate/clientidsecretkey
mosip.certify.authenticator.ida.audit-manager-url=https://${mosip.api.cre.internal.host}/v1/auditmanager/audits
mosip.certify.authenticator.ida.client-id=mosip-ida-client
mosip.certify.authenticator.ida.secret-key=${mosip.ida.client.secret}
mosip.certify.authenticator.ida.app-id=ida

## ------------------------------------------- UseCase specific default overriding properties ------------------------------------------------------------
mosip.certify.domain.url=https://${mosip.injicertify.mosipid.host:${mosip.injicertify.host}}
mosip.certify.identifier=${mosip.certify.domain.url}
mosip.certify.authorization.url=https://${mosipid.identity.esignet.host}
mosip.certify.database.name=inji_certify
# conditionally set the SOFTHSM pin based on the setup requirements and fallback to the latter if former value is missing
mosip.kernel.keymanager.hsm.keystore-pass=${softhsm.certify.mosipid.security.pin:${softhsm.certify.security.pin}}
# Add Display property for the issuer
mosip.certify.credential-config.issuer.display={\
  {\
    'name': 'MOSIP National ID',\
    'locale': 'en'\
  }\
}

logging.level.root=INFO
## Kyc Accepted Claims
mosip.certify.ida.kyc-exchange.accepted-claims=birthdate,address,gender,name,phone_number,picture,email,individual_id
## Kyc Accepted Locales
mosip.certify.ida.kyc-exchange.accepted-locales=en
## Add velocity template specific configurations
mosip.certify.data-provider-plugin.velocity-template.env-configs.uin_length=10
mosip.certify.data-provider-plugin.velocity-template.env-configs.vid_length=16
