# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

mosip.sunbird.url=http://10.3.1.146:8000/registry

## ------------------------------------------- Plugin enable properties ------------------------------------------------------------
mosip.certify.integration.scan-base-package=io.mosip.certify.sunbirdrc.integration
mosip.certify.integration.vci-plugin=SunbirdRCVCIssuancePlugin
mosip.certify.integration.audit-plugin=LoggerAuditService
mosip.certify.plugin-mode=VCIssuance

## ------------------------------------------- Plugin specific usecase properties ------------------------------------------------------------
mosip.certify.vciplugin.sunbird-rc.enable-psut-based-registry-search=false
#mosip.certify.vciplugin.sunbird-rc.issue-credential-url=${mosip.sunbird.url}/credentials-service/credentials/issue
mosip.certify.vciplugin.sunbird-rc.issue-credential-url=http://10.3.1.146:3000/credentials/issue
mosip.certify.vciplugin.sunbird-rc.supported-credential-types=LifeInsuranceCredential,InsuranceCredential

##Life Insurance Credential Configurations

mosip.certify.vciplugin.sunbird-rc.credential-type.LifeInsuranceCredential.static-value-map.issuerId=did:web:dharanidharan-s-04.github.io:mosipid-did:sunbird:b1189cf0-ba99-4f11-affb-2482859c1d93
mosip.certify.vciplugin.sunbird-rc.credential-type.LifeInsuranceCredential.template-url=${spring_config_url_env}/${spring.application.name}/${active_profile_env}/${spring_config_label_env}/life-insurance-credential.vm
mosip.certify.vciplugin.sunbird-rc.credential-type.LifeInsuranceCredential.registry-get-url=${mosip.sunbird.registry-url:${mosip.sunbird.url}}/api/v1/Insurance/
mosip.certify.vciplugin.sunbird-rc.credential-type.LifeInsuranceCredential.cred-schema-id=did:schema:6c54a775-6f54-4ac3-9684-f77008304741
mosip.certify.vciplugin.sunbird-rc.credential-type.LifeInsuranceCredential.cred-schema-version=1.0.0
mosip.certify.vciplugin.sunbird-rc.credential-type.LifeInsuranceCredential.registry-search-url=${mosip.sunbird.registry-url:${mosip.sunbird.url}}/api/v1/Insurance/search

##Insurance Credential Configurations
mosip.certify.vciplugin.sunbird-rc.credential-type.InsuranceCredential.static-value-map.issuerId=did:web:dharanidharan-s-04.github.io:mosipid-did:sunbird:b1189cf0-ba99-4f11-affb-2482859c1d93
mosip.certify.vciplugin.sunbird-rc.credential-type.InsuranceCredential.template-url=${spring_config_url_env}/${spring.application.name}/${active_profile_env}/${spring_config_label_env}/insurance-credential.vm
mosip.certify.vciplugin.sunbird-rc.credential-type.InsuranceCredential.registry-get-url=${mosip.sunbird.registry-url:${mosip.sunbird.url}}/api/v1/Insurance/
mosip.certify.vciplugin.sunbird-rc.credential-type.InsuranceCredential.cred-schema-id=did:schema:6c54a775-6f54-4ac3-9684-f77008304741
mosip.certify.vciplugin.sunbird-rc.credential-type.InsuranceCredential.cred-schema-version=1.0.0
mosip.certify.vciplugin.sunbird-rc.credential-type.InsuranceCredential.registry-search-url=${mosip.sunbird.registry-url:${mosip.sunbird.url}}/api/v1/Insurance/search

## ------------------------------------------- UseCase specific default overriding properties ------------------------------------------------------------
mosip.certify.domain.url=https://${mosip.injicertify.insurance.host:${mosip.injicertify.host}}
mosip.certify.identifier=${mosip.certify.domain.url}
mosip.certify.authorization.url=https://${mosipid.esignet.insurance.host}
mosip.certify.database.name=sunbird_inji_certify
spring.datasource.username=sunbirduser
# conditionally set the SOFTHSM pin based on the setup requirements and fallback to the latter if former value is missing
mosip.kernel.keymanager.hsm.keystore-pass=${softhsm.certify.insurance.security.pin:${softhsm.certify.security.pin}}
# Add Display property for the issuer
mosip.certify.credential-config.issuer.display={\
  {\
    'name': 'Insurance',\
    'locale': 'en'\
  }\
}
